version: '3.8'
services:
  mysql:
    image: "public.ecr.aws/bitnami/mysql:5.7.33"
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
volumes:
  db_data: {}
